name: Publish Package to npmjs
on:
  push:
    tags:
      - "cli-v*"

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v6
      - run: pnpm ci
      - run: pnpm run build
        working-directory: packages/binderbot
      - run: pnpm publish --provenance --access public --no-git-checks
        working-directory: packages/binderbot
